-- 初始化管理员用户（密码：admin）
INSERT INTO `sys_user` (`username`, `password`, `email`, `full_name`, `enabled`, `create_time`, `update_time`) SELECT 'admin', '$2a$10$ItcO6sO0aIAV8sJU3NUwqu/Fwl9KqGzM8zdZhTMxv5ZDWBmYYHa62', 'admin@example.com', '系统管理员', 1, UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_user` WHERE `username` = 'admin');

-- 初始化角色
INSERT INTO `sys_role` (`name`, `code`, `description`, `create_time`, `update_time`) SELECT '管理员', 'ADMIN', '系统管理员，拥有所有权限', UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_role` WHERE `code` = 'ADMIN');
INSERT INTO `sys_role` (`name`, `code`, `description`, `create_time`, `update_time`) SELECT '普通用户', 'USER', '普通用户，拥有基本权限', UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_role` WHERE `code` = 'USER');

-- 初始化权限（菜单）
-- 顶级菜单
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system', '系统管理', '系统管理菜单', 'menu', '/system', null, 'SettingOutlined', 1, 0, UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'dashboard', '仪表盘', '仪表盘菜单', 'menu', '/dashboard', null, 'DashboardOutlined', 0, 0, UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'dashboard');

-- 系统管理子菜单
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:user', '用户管理', '用户管理菜单', 'menu', '/user', null, 'UserOutlined', 1, (SELECT id FROM `sys_permission` WHERE `code` = 'system'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:user');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:role', '角色管理', '角色管理菜单', 'menu', '/role', null, 'TeamOutlined', 2, (SELECT id FROM `sys_permission` WHERE `code` = 'system'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:role');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:permission', '权限管理', '权限管理菜单', 'menu', '/permission', null, 'KeyOutlined', 3, (SELECT id FROM `sys_permission` WHERE `code` = 'system'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:permission');

-- 初始化权限（按钮）
-- 用户管理按钮
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:user:list', '用户列表', '查看用户列表', 'button', null, null, null, 1, (SELECT id FROM `sys_permission` WHERE `code` = 'system:user'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:user:list');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:user:add', '添加用户', '添加用户', 'button', null, null, null, 2, (SELECT id FROM `sys_permission` WHERE `code` = 'system:user'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:user:add');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:user:edit', '编辑用户', '编辑用户', 'button', null, null, null, 3, (SELECT id FROM `sys_permission` WHERE `code` = 'system:user'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:user:edit');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:user:delete', '删除用户', '删除用户', 'button', null, null, null, 4, (SELECT id FROM `sys_permission` WHERE `code` = 'system:user'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:user:delete');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:user:query', '查询用户', '查询用户详情', 'button', null, null, null, 5, (SELECT id FROM `sys_permission` WHERE `code` = 'system:user'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:user:query');

-- 角色管理按钮
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:role:list', '角色列表', '查看角色列表', 'button', null, null, null, 1, (SELECT id FROM `sys_permission` WHERE `code` = 'system:role'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:role:list');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:role:add', '添加角色', '添加角色', 'button', null, null, null, 2, (SELECT id FROM `sys_permission` WHERE `code` = 'system:role'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:role:add');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:role:edit', '编辑角色', '编辑角色', 'button', null, null, null, 3, (SELECT id FROM `sys_permission` WHERE `code` = 'system:role'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:role:edit');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:role:delete', '删除角色', '删除角色', 'button', null, null, null, 4, (SELECT id FROM `sys_permission` WHERE `code` = 'system:role'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:role:delete');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:role:query', '查询角色', '查询角色详情', 'button', null, null, null, 5, (SELECT id FROM `sys_permission` WHERE `code` = 'system:role'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:role:query');

-- 权限管理按钮
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:permission:list', '权限列表', '查看权限列表', 'button', null, null, null, 1, (SELECT id FROM `sys_permission` WHERE `code` = 'system:permission'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:permission:list');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:permission:add', '添加权限', '添加权限', 'button', null, null, null, 2, (SELECT id FROM `sys_permission` WHERE `code` = 'system:permission'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:permission:add');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:permission:edit', '编辑权限', '编辑权限', 'button', null, null, null, 3, (SELECT id FROM `sys_permission` WHERE `code` = 'system:permission'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:permission:edit');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:permission:delete', '删除权限', '删除权限', 'button', null, null, null, 4, (SELECT id FROM `sys_permission` WHERE `code` = 'system:permission'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:permission:delete');
INSERT INTO `sys_permission` (`code`, `name`, `description`, `type`, `path`, `component`, `icon`, `sort`, `parent_id`, `create_time`, `update_time`) SELECT 'system:permission:query', '查询权限', '查询权限详情', 'button', null, null, null, 5, (SELECT id FROM `sys_permission` WHERE `code` = 'system:permission'), UNIX_TIMESTAMP(NOW()) * 1000, UNIX_TIMESTAMP(NOW()) * 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_permission` WHERE `code` = 'system:permission:query');

-- 为管理员角色分配所有权限
INSERT INTO `sys_role_permission` (`role_id`, `permission_id`) SELECT (SELECT id FROM `sys_role` WHERE `code` = 'ADMIN'), p.id FROM `sys_permission` p WHERE NOT EXISTS (SELECT 1 FROM `sys_role_permission` rp WHERE rp.role_id = (SELECT id FROM `sys_role` WHERE `code` = 'ADMIN') AND rp.permission_id = p.id);

-- 为普通用户角色分配基本权限
INSERT INTO `sys_role_permission` (`role_id`, `permission_id`) SELECT (SELECT id FROM `sys_role` WHERE `code` = 'USER'), p.id FROM `sys_permission` p WHERE p.`code` IN ('dashboard', 'system:user:list', 'system:user:query') AND NOT EXISTS (SELECT 1 FROM `sys_role_permission` rp WHERE rp.role_id = (SELECT id FROM `sys_role` WHERE `code` = 'USER') AND rp.permission_id = p.id);

-- 为管理员用户分配管理员角色
INSERT INTO `sys_user_role` (`user_id`, `role_id`) SELECT (SELECT id FROM `sys_user` WHERE `username` = 'admin'), (SELECT id FROM `sys_role` WHERE `code` = 'ADMIN') WHERE NOT EXISTS (SELECT 1 FROM `sys_user_role` ur WHERE ur.user_id = (SELECT id FROM `sys_user` WHERE `username` = 'admin') AND ur.role_id = (SELECT id FROM `sys_role` WHERE `code` = 'ADMIN'));
